name: be_safe
description: Application de sÃ©curitÃ© pour trajets et retours Ã  domicile
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ðŸ” Authentification Supabase
  supabase_flutter: ^2.0.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  flutter_typeahead: ^5.2.0
  # ðŸ—ºï¸ Carte interactive
  flutter_map: ^6.2.1
  latlong2: ^0.9.1
  http: ^1.2.1

  # ðŸ“ Localisation et gÃ©ocodage
  geolocator: ^10.1.1
  geocoding: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
